Traceback (most recent call last):
  File "c:\users\meyjoh\repos\vlcompimg\compimg\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\meyjoh\repos\vlcompimg\compimg\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\meyjoh\repos\vlcompimg\compimg\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\meyjoh\repos\vlcompimg\compimg\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\meyjoh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\meyjoh\repos\vlcompimg\compimg\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\meyjoh\repos\vlcompimg\compimg\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\meyjoh\repos\vlcompimg\compimg\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# images to combine
img_1 = imread('tiger.png')
#img_2 = imread('tiger.png')
img_2 = imread('puma.png')

print(img_1.shape)
print(img_2.shape)
# function to work with gray scales
def rgb2gray(img) -> np.ndarray:
    r, g, b = img[:,:,0], img[:,:,1], img[:,:,2] 
    gamma = 1.04

    r_cte, g_cte, b_cte = 0.2126, 0.7152, 0.0722
    gray_img = r_cte * r ** gamma + g_cte * g ** gamma + b_cte * b ** gamma
    
    return gray_img

# gray scale images, for low and high pass filters
img_low = rgb2gray(img_1)[33:335,]
img_high = rgb2gray(img_2)


# plot of images
_, (ax1, ax2) = plt.subplots(1, 2)
figure_size = plt.gcf().get_size_inches()
plt.gcf().set_size_inches(figure_size)
ax1.imshow(img_low, cmap="gray")
ax2.imshow(img_high, cmap="gray")
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-4-9605244d91b4>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# images to combine[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mimg_1[0m [1;33m=[0m [0mimread[0m[1;33m([0m[1;34m'tiger.png'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;31m#img_2 = imread('tiger.png')[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mimg_2[0m [1;33m=[0m [0mimread[0m[1;33m([0m[1;34m'puma.png'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mNameError[0m: name 'imread' is not defined
NameError: name 'imread' is not defined

